version: '3.2'
services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - 80:8080
    volumes:
      - ./www/task/:/var/www/task/

  php:
    image: php:8.1-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/task/:/var/www/task/

