version: '3.2'
services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - .:/var/www/task

  php:
    image: php:8.1-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - .:/var/www/task/

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: mynewpassword
      MYSQL_DATABASE: Users
