version: '3.2'
services:
  nginx:
    build: nginx
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./../:/var/www/task

  php:
    image: php:8.1-fpm
    build: php
    container_name: php-container
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=Users
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mynewpassword
    depends_on:
      - mysql
    expose:
      - 9000
    volumes:
      - ./../:/var/www/task/


  mysql:
    image: mysql:5.7
    build: sql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mynewpassword
      MYSQL_HOST: localhost
      MYSQL_DATABASE: Users
      MYSQL_USER: root

